# Generated by Django 4.1.7 on 2023-03-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_active_alter_employee_full_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
