# Generated by Django 4.1.7 on 2023-03-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(choices=[('contractor', 'Contractor'), ('planilla', 'Planilla')], max_length=20),
        ),
    ]
