# Generated by Django 4.1.7 on 2023-03-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_assignation_employee_current_assignation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
