# Generated by Django 4.1.7 on 2023-03-14 18:04

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_address_employee_birthdate_employee_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dni',
        ),
        migrations.AddField(
            model_name='employee',
            name='child_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='civil_status',
            field=models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='dishability_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_1',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_1_number',
            field=models.CharField(max_length=256, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_1_relationship',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_2',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_2_number',
            field=models.CharField(max_length=256, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_2_relationship',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_number',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='id_type',
            field=models.CharField(choices=[('dni', 'DNI')], default='1', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='is_dishabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_1',
            field=models.CharField(max_length=256, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_2',
            field=models.CharField(max_length=256, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=60, null=True),
        ),
    ]
